tracer.property: "I AM 669"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      validation-query: "SELECT 1"
      test-while-idle: true
mybatis:
  #mapper目录
  mapper-locations: classpath:mapper/*.xml
  #实体类目录
  type-aliases-package: com.company.vo
  configuration:
    map-underscore-to-camel-case: true
